### ISSUE TITLE
[REQUEST Membership]: New membership for fsl

### ISSUE THREAD

**Issue by fengshunli** [openkruise/community#10]
## GitHub Username
@fengshunli 

## Organization you are requesting membership in

openkruise

## Sponsors

@veophi  @zmberg @furykerry 

## Requirements

- [x] I have joined in the community *Slack* or *DingTalk*
- [x] I often attend OpenKruise Community Week
- [x] I have reviewed the [community-membership] docs
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenKruise subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/openkruise/kruise/pull/1172
https://github.com/openkruise/kruise/pull/1166
https://github.com/openkruise/openkruise.io/pull/92

- Issues :
https://github.com/openkruise/kruise/issues/1167
https://github.com/openkruise/kruise/issues/1169

[devstats]: https://openkruise.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community-membership]: https://github.com/openkruise/community/blob/master/community-membership.md
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by zmberg** [comment]
+1 welcome onboard ! Thanks for contributing to OpenKruise.

**Comment by veophi** [comment]
+1 welcome！

**Comment by furykerry** [comment]
+1 welcome onboard
