### ISSUE TITLE
[REQUEST Membership]: New membership for <ls-2018>

### ISSUE THREAD

**Issue by ls-2018** [openkruise/community#11]
## GitHub Username

ls-2018
## Organization you are requesting membership in

openkruise

## Requirements

- [x] I have joined in the community *Slack* or *DingTalk*
- [x] I often attend OpenKruise Community Week
- [x] I have reviewed the [community-membership] docs
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenKruise subprojects

## List of your contributions 
- PRs reviewed / authored:
    - https://github.com/openkruise/kruise/pull/1391
    - https://github.com/openkruise/kruise/pull/1373
    - https://github.com/openkruise/kruise/pull/1355
    - https://github.com/openkruise/charts/pull/64
    - https://github.com/openkruise/kruise/pull/1374
    - https://github.com/openkruise/openkruise.io/pull/135
    - https://github.com/openkruise/openkruise.io/pull/134
    - https://github.com/openkruise/openkruise.io/pull/132
    - https://github.com/openkruise/openkruise.io/pull/130
    - https://github.com/openkruise/openkruise.io/pull/129
    - https://github.com/openkruise/openkruise.io/pull/127
    - https://github.com/openkruise/openkruise.io/pull/125
    - https://github.com/openkruise/openkruise.io/pull/124
    - https://github.com/openkruise/openkruise.io/pull/139
    - https://github.com/openkruise/openkruise.io/pull/136
    - https://github.com/openkruise/kruise/pull/1418
    - https://github.com/openkruise/kruise/pull/1413
    - https://github.com/openkruise/kruise/pull/1410
    - https://github.com/openkruise/kruise/pull/1399
    - https://github.com/openkruise/kruise/pull/1387
    - https://github.com/openkruise/kruise/pull/1385
- Issues :
    - https://github.com/openkruise/kruise/issues/1406
    - https://github.com/openkruise/kruise/issues/1411
    
    
[devstats]: https://openkruise.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community-membership]: https://github.com/openkruise/community/blob/master/community-membership.md
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by furykerry** [comment]
agree +1

**Comment by zmberg** [comment]
agree +1

**Comment by veophi** [comment]
agree +1

welcome!

**Comment by furykerry** [comment]
@ls-2018 Congratulations and welcome onboard 

You should receive an email that invite you to become member of OpenKruise.
And remember to change your organization visibility to public. https://github.com/orgs/openkruise/people
