### ISSUE TITLE
Apply to become an OpenKruise Member

### ISSUE THREAD

**Issue by hantmac** [openkruise/community#2]
Hi there,
   I don’t know if I am eligible to be an OpenKruise Member but I am interested in OpenKruise and have been using OpenKruise for a long time.  I hope that I can become a member of OpenKruise Member and make much more contributions to Kuise community. 

  If not, it’s okay, I will continue to follow the community.

                                                                                               Best Wishes.

**Comment by FillZpp** [comment]
@hantmac Sure, it's ok for me. Please submit a PR with the `Membership Request` template.

**Comment by hantmac** [comment]
@FillZpp  Thanks!  And where is the `Membership Request template` ? I can't find it anywhere 🤔.

**Comment by FillZpp** [comment]
You will find a `Get started` button for `Membership Request`, when you try to new a issue in this repo.
