### ISSUE TITLE
[REQUEST Membership]: New membership for <hantmac>

### ISSUE THREAD

**Issue by hantmac** [openkruise/community#3]
## GitHub Username
hantmac

## Organization you are requesting membership in

openkruise

## Sponsors
@FillZpp 

## Requirements

- [x] I have joined in the community *Slack* or *DingTalk*
- [ ] I often attend OpenKruise Community Week
- [x] I have reviewed the [community-membership] docs
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenKruise subprojects

## List of your contributions 
- PRs reviewed / authored:
- https://github.com/openkruise/kruise/pull/620
- https://github.com/openkruise/kruise/pull/404
- https://github.com/openkruise/kruise-tools/pull/4
- https://github.com/openkruise/kruise-tools/pull/2
- https://github.com/openkruise/kruise-tools/pull/1
- reviewed https://github.com/openkruise/kruise/pull/617
- reviewed https://github.com/openkruise/kruise/pull/673

- Issues : 
- https://github.com/openkruise/kruise/issues/628
- https://github.com/openkruise/kruise/issues/624
- https://github.com/openkruise/kruise/issues/582
- https://github.com/openkruise/kruise/issues/581
- https://github.com/openkruise/kruise/issues/453
- https://github.com/openkruise/kruise/issues/348

[devstats]: https://openkruise.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community-membership]: https://github.com/openkruise/community/blob/master/community-membership.md
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by FillZpp** [comment]
agree +1

WDYT @furykerry @Fei-Guo

**Comment by furykerry** [comment]
agree +1

**Comment by Fei-Guo** [comment]
+1

**Comment by FillZpp** [comment]
@hantmac Congratulate you to become a member of OpenKruise community. We have sent a github message to invite you as member of OpenKruise, please check the message and keep [your membership](https://github.com/orgs/openkruise/people) public.

**Comment by hantmac** [comment]
Thank you everybody! I will work hard to make more contributions to community!

**Comment by FillZpp** [comment]
@hantmac Please remember to change your visibility [here](https://github.com/orgs/openkruise/people) from `Private` to `Public`.

**Comment by hantmac** [comment]
> @hantmac Please remember to change your visibility [here](https://github.com/orgs/openkruise/people) from `Private` to `Public`.

Thanks! Have changed.
