### ISSUE TITLE
[REQUEST Membership]: New membership for chrisliu1995

### ISSUE THREAD

**Issue by chrisliu1995** [openkruise/community#9]
## GitHub Username
chrisliu1995

## Organization you are requesting membership in
openkruise

## Sponsors
@FillZpp 

## Requirements

- [x] I have joined in the community *Slack* or *DingTalk*
- [x] I often attend OpenKruise Community Week
- [x] I have reviewed the [community-membership] docs
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])
- [x] I am actively contributing to 1 or more OpenKruise subprojects

## List of your contributions 
- PRs reviewed / authored:

  - https://github.com/openkruise/kruise-game/pull/2
  - https://github.com/openkruise/kruise-game/pull/7
  - https://github.com/openkruise/kruise-game/pull/8
  - https://github.com/openkruise/kruise-game/pull/9
  - https://github.com/openkruise/kruise-game/pull/10
  - https://github.com/openkruise/kruise-game/pull/11
  - https://github.com/openkruise/kruise-game/pull/16
  - https://github.com/openkruise/kruise-game/pull/19

- Issues :
  - https://github.com/openkruise/kruise-game/issues/15

[devstats]: https://openkruise.devstats.cncf.io/d/56/company-commits-table?orgId=1
[community-membership]: https://github.com/openkruise/community/blob/master/community-membership.md
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by FillZpp** [comment]
+1 welcome! Thanks for building up and actively contributing to kruise-game.

**Comment by furykerry** [comment]
+1 welcome onboard ! Thanks for contributing to kruise-game.

**Comment by FillZpp** [comment]
@chrisliu1995 Congratulations! 🎉

You should receive an email that invite you to become member of OpenKruise.
And remember to change your organization visibility to public. https://github.com/orgs/openkruise/people

/close
